
export const SKILLS = [
  {
    category: "Frontend Development",
    items: [
      { name: "HTML / CSS / JavaScript", level: 95 },
      { name: "React.js / Next.js", level: 90 },
      { name: "Responsive Design", level: 90 },
      { name: "React Native", level: 85 },
      { name: "Cross-Browser Compatibility", level: 85 },
      { name: "Tailwind CSS", level: 80 },
      { name: "SASS", level: 80 },
      { name: "API Integration (REST, GraphQL)", level: 80 },
      { name: "Accessibility", level: 80 },
      { name: "Version Control (Git)", level: 80 },
      { name: "TypeScript", level: 75 },
      { name: "Performance Optimization", level: 75 },
      { name: "State Management (Redux, Context API)", level: 75 },
      { name: "UI/UX Principles", level: 75 },
      
    ],
  },
  {
    category: "Backend Development",
    items: [
      { name: "Node.js / Express", level: 85 },
      { name: "REST & GraphQL APIs", level: 85 },
      { name: "PostgreSQL / MongoDB", level: 80 },
      { name: "Authentication & Authorization", level: 75 },
      { name: "Mongoose", level: 75 },
      

    ],
  },
  {
    category: "Tools & Other Tech Skills",
    items: [
      { name: "Git & GitHub", level: 90 },
      { name: "Visual Studio Code", level: 90 },
      { name: "npm / Yarn", level: 90 },
      { name: "Chrome DevTools", level: 85 },
      { name: "ESLint / Prettier", level: 85 },
      { name: "Deployment (Netlift, Render)", level: 85 },
      { name: "Postman", level: 80 },
      { name: "Zoom", level: 80 },
      { name: "Expo", level: 80 },
      { name: "Microsoft Teams", level: 80 },
      { name: "Markdown", level: 80 },
      { name: "Redux DevTools", level: 80 },
      { name: "Bootstrap", level: 75 },
      { name: "Email Marketing Tools (Mailchimp, SendGrid)", level: 70 },
      { name: "Figma (Basic UI/UX Design)", level: 60 },
      { name: "AWS Basics", level: 50 },
      { name: "Video Editing Tools (Adobe Premiere Pro, Final Cut Pro)", level: 50 },
      { name: "3D Modeling Tools (Blender, Maya)", level: 40 },
      { name: "Game Development Basics (Unity, Unreal Engine)", level: 40 },
    ],
  },
  {
    category: "Applicable Non Technical Skills",
    items: [
      { name: "Attention to Detail", level: 99 },
      { name: "Communication", level: 95 },
      { name: "Adaptability", level: 95 },
      { name: "Problem-Solving", level: 90 },
      { name: "Stress Management", level: 90 },
      { name: "Leadership", level: 90 },
      { name: "Team Collaboration", level: 90 },
      { name: "Time Management", level: 90 },
      { name: "Critical Thinking", level: 85 },
      { name: "Continuous Learning", level: 85 },
      { name: "Creativity", level: 80 },
      { name: "Networking", level: 80 },
      { name: "Conflict Resolution", level: 80 },
      { name: "Emotional Intelligence", level: 80 },
      { name: "Project Management", level: 70 },
    ],
  },
];
